### Send POST request with json body
POST /ReserveProduct HTTP/1.1
Host: 127.0.0.1:8081
Content-Type: application/json

{
  "warehouse_id": 2,
  "unique_codes": [
    "olkiuj",
    "tghyuj"
  ],
  "counts": [
    1000,
    1200
  ]
}

### Send POST request with json body
POST /FreeReservation HTTP/1.1
Host: 127.0.0.1:8081
Content-Type: application/json

{
"id": [17]
}

### Send POST request with json body
POST /GetAllProducts HTTP/1.1
Host: 127.0.0.1:8081
Content-Type: application/json

{
  "warehouse_id": 3
}