DROP TABLE product CASCADE;
DROP TABLE warehouse CASCADE;
DROP TABLE warehouse_product CASCADE;
DROP TABLE reservation CASCADE;
DROP TABLE users CASCADE;
DROP TABLE jwt CASCADE;
DROP TABLE users_role CASCADE;