// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import ()

type Jwt struct {
	UserID       string
	AccessToken  string
	RefreshToken string
}

type User struct {
	ID           string
	Login        string
	PasswordHash string
}

type UsersRole struct {
	UserID string
	Role   int32
}
